# Traefik Dynamic Configuration
# This file contains dynamic configuration for Traefik

http:
  # Middlewares
  middlewares:
    # Security headers
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive"
    
    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
    
    # IP whitelist (example - adjust as needed)
    # ip-whitelist:
    #   ipWhiteList:
    #     sourceRange:
    #       - "192.168.1.0/24"
    #       - "10.0.0.0/8"
    
    # Compression
    compression:
      compress: {}

  # Services (for custom backends if needed)
  services: {}

  # Routers (additional custom routes if needed)
  routers: {}

# TCP/UDP configurations
tcp: {}
udp: {}

# TLS configuration
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"